apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-via-google-clouddns
  namespace: openshift-cert-manager
spec:
  acme:
    email: goern+nostromo-acme@b4mad.net
    privateKeySecretRef:
      name: acme-google-clouddns
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          project: aicoe-prow  # ja confusing, the title is `aicoe-operate-first`
          serviceAccountSecretRef:
            name: google-clouddns-nostromo-dns01-solver
            key: aicoe-prow-96c1a6bfd097.json
      selector:
        dnsZones:
        - b4mad.emea.operate-first.cloud
