apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  app.kubernetes.io/managed-by: human+kustomize/command-line
  app.kubernetes.io/part-of: op1st-emea-b4mad-nostromo
  org.opencontainers.image.source: https://github.com/goern/op1st-emea-b4mad-nostromo.git

resources:
- image-registry-patch.yaml
- image-registry-storage-pvc.yaml

patches:
- target:
    group: imageregistry.operator.openshift.io
    version: v1
    kind: Config
    name: cluster
  patch: |-
    - op: replace
      path: /spec/managementState
      value: Managed
    - op: replace
      path: /spec/storage
      value:
        pvc:
          claim: image-registry-storage
