apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      retention: 72h
      retentionSize: 30GB
      volumeClaimTemplate:
        spec:
          storageClassName: lvms-vg1
          resources:
            requests:
              storage: 40Gi
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          storageClassName: lvms-vg1
          resources:
            requests:
              storage: 10Gi
