---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  app.kubernetes.io/managed-by: human+kustomize/command-line
  app.kubernetes.io/part-of: op1st-emea-b4mad-nostromo
  org.opencontainers.image.source: https://github.com/b4mad/op1st-emea-b4mad-nostromo.git

resources:
  - https://github.com/redhat-cop/gitops-catalog/openshift-gitops-operator/operator/overlays/latest?ref=main
  - https://github.com/redhat-cop/gitops-catalog/openshift-pipelines-operator/overlays/latest?ref=main
